// DO NOT MODIFY, THIS FILE IS GENERATED FROM version.in.hh
//
// @PROJECT_NAME@/@PROJECT_VERSION@@PROJECT_VERSION_STABILITY@
//
// Copyright (c) 2026 Marcin Zdun
// This code is licensed under MIT license (see LICENSE for details)
// clang-format off

#pragma once

#define BF_VERSION_STR "@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"
#define BF_VERSION_STR_SHORT "@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@"
#define BF_VERSION_STABILITY "@PROJECT_VERSION_STABILITY@"
#define BF_VERSION_BUILD_META "@PROJECT_VERSION_BUILD_META@"
#define BF_PROJECT_NAME "@PROJECT_NAME@"

#define BF_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define BF_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define BF_VERSION_PATCH @PROJECT_VERSION_PATCH@
// clang-format on
