name: Build

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

env:
  RELEASE: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}

jobs:
  M:
    name: Prepare builds
    runs-on: ubuntu-latest
    outputs:
      release: ${{fromJson(env.RELEASE)}}
      matrix: ${{steps.flow.outputs.matrix}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find builds
        id: flow
        run: python ./.flow/flow.py github matrix

  build:
    needs: M
    strategy:
      matrix: ${{ fromJson(needs.M.outputs.matrix) }}

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      CONAN_REVISIONS_ENABLED: 1
      FLOW_COMMAND: python ./.flow/flow.py run -D os=${{ matrix.os }} build_type=${{ matrix.build_type }} compiler=${{ matrix.compiler }} sanitizer=${{ matrix.sanitizer }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARTIFACT_SUFFIX: ${{ matrix.github_os }}-${{ matrix.build_type }}-${{ matrix.compiler }}${{ matrix.sanitizer && '-sanitize' || '' }}
      CONAN_CACHE: ${{ matrix.github_os }}-${{ matrix.build_type }}-${{ matrix.compiler }}
      RELEASE: ${{needs.M.outputs.release}}

    runs-on: ${{ matrix.github_os }}
    name: ${{ matrix.build_name }}
    outputs:
      release: ${{fromJson(env.RELEASE)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      #     ######## ##    ## ##     ## #### ########   #######  ##    ## ##     ## ######## ##    ## ########
      #     ##       ###   ## ##     ##  ##  ##     ## ##     ## ###   ## ###   ### ##       ###   ##    ##
      #     ##       ####  ## ##     ##  ##  ##     ## ##     ## ####  ## #### #### ##       ####  ##    ##
      #     ######   ## ## ## ##     ##  ##  ########  ##     ## ## ## ## ## ### ## ######   ## ## ##    ##
      #     ##       ##  ####  ##   ##   ##  ##   ##   ##     ## ##  #### ##     ## ##       ##  ####    ##
      #     ##       ##   ###   ## ##    ##  ##    ##  ##     ## ##   ### ##     ## ##       ##   ###    ##
      #     ######## ##    ##    ###    #### ##     ##  #######  ##    ## ##     ## ######## ##    ##    ##
      - name: Bootstrap
        uses: proj-flow-actions/bootstrap@v1
        with:
          cache-prefix: ${{ matrix.github_os }}
          python-version: "3.12"
          checkout: true
          submodules: true
      - name: Setup Windows
        if: ${{ matrix.windows }}
        uses: proj-flow-actions/setup-windows@v1
        with:
          install-occ: ${{ matrix.build_type == 'Debug' }}

      - name: Setup Ubuntu
        if: ${{ matrix.ubuntu }}
        uses: proj-flow-actions/setup-ubuntu@v1
        with:
          gcc-ppa: ${{ matrix.needs_gcc_ppa }}
          gcc-version: ${{ matrix.gcc_ver }}
          compiler: ${{ matrix.compiler }}

      - name: Setup Conan
        uses: proj-flow-actions/setup-conan@v1
        with:
          user-directory: ${{ matrix.home }}
          cache-prefix: ${{ env.CONAN_CACHE }}

      #     ########  ########   #######        ## ########  ######  ########
      #     ##     ## ##     ## ##     ##       ## ##       ##    ##    ##
      #     ##     ## ##     ## ##     ##       ## ##       ##          ##
      #     ########  ########  ##     ##       ## ######   ##          ##
      #     ##        ##   ##   ##     ## ##    ## ##       ##          ##
      #     ##        ##    ##  ##     ## ##    ## ##       ##    ##    ##
      #     ##        ##     ##  #######   ######  ########  ######     ##

      - name: Configure
        run: ${{ env.FLOW_COMMAND }} -s Conan,CMake

      - name: Build
        run: ${{ env.FLOW_COMMAND }} -s Build

      - name: Test
        run: ${{ env.FLOW_COMMAND }} -s Test,StoreTests

      - name: Pack
        id: artifacts
        if: ${{ fromJson(env.RELEASE) }}
        run: ${{ env.FLOW_COMMAND }} -s Sign,Pack,SignPackages,StorePackages
        env:
          SIGN_TOKEN: ${{ secrets.SIGN_TOKEN }}

      #     ##     ## ########  ##        #######     ###    ########
      #     ##     ## ##     ## ##       ##     ##   ## ##   ##     ##
      #     ##     ## ##     ## ##       ##     ##  ##   ##  ##     ##
      #     ##     ## ########  ##       ##     ## ##     ## ##     ##
      #     ##     ## ##        ##       ##     ## ######### ##     ##
      #     ##     ## ##        ##       ##     ## ##     ## ##     ##
      #      #######  ##        ########  #######  ##     ## ########

      - name: Upload packages
        uses: actions/upload-artifact@v4
        if: ${{ steps.artifacts.outputs.CPACK_GENERATORS != '' }}
        with:
          name: _packages-${{ env.ARTIFACT_SUFFIX }}
          path: ${{github.workspace}}/build/artifacts/packages/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: _tests-${{ env.ARTIFACT_SUFFIX }}
          path: ${{github.workspace}}/build/artifacts/test-results/

  merge:
    name: Merge artifacts
    runs-on: ubuntu-latest
    needs: build
    env:
      RELEASE: ${{needs.build.outputs.release}}
    outputs:
      release: ${{fromJson(env.RELEASE)}}

    steps:
      - name: Merge packages
        uses: actions/upload-artifact/merge@v4
        if: ${{ fromJson(env.RELEASE) }}
        with:
          name: Packages
          pattern: _packages-*
          delete-merged: true
      - name: Merge test results
        uses: actions/upload-artifact/merge@v4
        if: always()
        with:
          name: Test Results
          pattern: _tests-*
          delete-merged: true

  publish:
    name: Upload packages
    if: ${{ fromJson(needs.merge.outputs.release) }}
    needs: merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      RELEASE: ${{needs.merge.outputs.release}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: ${{github.workspace}}/build/download/packages

      - name: Publish the release
        run: python ./.flow/flow.py github publish --upload "${{github.workspace}}/build/download/packages"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
